services:
  app-1:
    build: .
    command: sh -c './wait-for redis:6379'
    command: sh -c './wait-for mongo:27017'
    command: sh -c './wait-for rabbit:5672 -- ./cat'
    depends_on:
      - mongo
      - redis
      - rabbit
    ports:
      - "8081:8081"
    container_name: app-1
    restart: on-failure
    networks: 
      - cat-service
  
  app-2:
    build: .
    command: sh -c './wait-for redis:6379'
    command: sh -c './wait-for mongo:27017'
    command: sh -c './wait-for rabbit:5672 -- ./cat'
    depends_on:
      - mongo
      - redis
      - rabbit
    ports:
      - "8082:8081"
    container_name: app-2
    restart: on-failure
    networks: 
      - cat-service
  
  mongo: 
    image: mongo
    ports: 
      - "27017:27017"
    container_name: mongo
    restart: on-failure
    networks: 
      - cat-service

  redis:
    image: redis
    depends_on:
      - mongo
    ports: 
      - "6379:6379"
    container_name: redis
    restart: on-failure
    networks: 
      - cat-service

  rabbit:
    image: rabbitmq
    ports:
    - "5672:5672"
    container_name: rabbit
    restart: on-failure
    networks:
      - cat-service

      


networks: 
  cat-service:
    driver: bridge